<!DOCTYPE html>
<!-- including this file will show a navigation bar across the top of the page to get around the site -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #dddddd;
        }

        li {
            float: left;
        }

        li a {
            display: block;
            padding: 8px;
        }
    </style>
</head>
<body>
<ul>
    <li><a href="./index.php">Home</a></li>
    <li><a href="./menu.php">Menu</a></li>
    <li><a href="./categories.php">Categories</a></li>
    <li><a href="./cart.php">Cart</a></li>
    <li><a href="./account.php">Account</a></li>
</ul>
</body>
</html>